#线上配置文件
spring:
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/auto_canary
    username: {youraccount}   #example:root
    password: {yourpassword}   #example:123456
  # session 失效时间
  session:
    timeout: 86400
server:
  address: 0.0.0.0